apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus-stack
  namespace: monitoring
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: kube-prometheus-stack
  targetNamespace: monitoring
  valuesContent: |
    defaultRules:
      create: true
    alertmanager:
      enabled: true
      service:
        type: ClusterIP
    grafana:
      enabled: true
      service:
        type: ClusterIP
      adminPassword: "admin"
    prometheus:
      enabled: true
      service:
        type: ClusterIP
      prometheusSpec:
        retention: 7d
        retentionSize: 10GB
        serviceMonitorSelectorNilUsesHelmValues: false
        podMonitorSelectorNilUsesHelmValues: false
        ruleSelectorNilUsesHelmValues: false
        probeSelectorNilUsesHelmValues: false
