apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: visitor-app
  namespace: monitoring
  labels:
    app: visitor-app
spec:
  selector:
    matchLabels:
      app: visitor-app
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis
  namespace: monitoring
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  endpoints:
  - port: redis
    interval: 30s
