apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - redis-deployment.yaml

commonLabels:
  app: visitor-app
  project: gitops-demo
