apiVersion: v1
kind: Service
metadata:
  name: visitor-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "5000"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: visitor-app
  ports:
  - name: http
    port: 80
    targetPort: 5000
  - name: metrics  
    port: 5000
    targetPort: 5000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"  
spec:
  selector:
    app: redis
  ports:
  - name: redis
    port: 6379
    targetPort: 6379
  - name: metrics  
    port: 9121
    targetPort: 9121
