name: Build and Push to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This gives the workflow permission to push
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./app
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/visitor-app:latest

    - name: Update deployment manifest
      run: |
        sed -i 's|YOUR_DOCKER_USERNAME/visitor-app:latest|${{ secrets.DOCKER_USERNAME }}/visitor-app:latest|g' k8s/base/deployment.yaml

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add k8s/base/deployment.yaml
        git diff --staged --quiet || git commit -m "CI: Update image to ${{ secrets.DOCKER_USERNAME }}/visitor-app:latest"
        git push
